import type { KnowledgeDocument, KnowledgeDocumentType, KnowledgeLanguage } from './types';

export const SEED_DOCUMENTS: Omit<KnowledgeDocument, 'id' | 'version' | 'status' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Emergency Evacuation Procedure',
    content: 'EMERGENCY EVACUATION PROCEDURE\n\nPurpose: To establish a standard procedure for evacuating the stadium in case of an emergency.\n\nScope: Applies to all stadium personnel, contractors, and fans.\n\nProcedure:\n1. When evacuation is ordered, all gates must be opened simultaneously by the Gate Operations team.\n2. Staff at each section shall guide fans to the nearest exit using pre-assigned routes.\n3. PA system broadcasts evacuation message in English, Spanish, French, and Arabic.\n4. Medical teams stage at first aid stations and await further instructions.\n5. Head count is conducted at designated rally points outside the venue.\n6. Command center confirms all-clear before allowing re-entry.\n\nKey Contacts:\n- Command Center: Radio Channel 1\n- Medical Coordinator: Radio Channel 3\n- Security Lead: Radio Channel 2\n\nRally Points:\n- North Rally: Parking Lot North (Zone A)\n- South Rally: Parking Lot South (Zone B)\n- East Rally: City Park (East Exit)\n- West Rally: Community Center (West Exit)',
    type: 'emergency',
    language: 'en',
    stadiumId: 'all',
    tags: ['evacuation', 'emergency', 'safety', 'procedure'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Standard procedure for full stadium evacuation including gate operations, PA broadcasts, medical staging, and rally points.',
    metadata: { department: 'Operations', priority: 'critical', reviewCycle: 'annual' },
  },
  {
    title: 'Medical Emergency Response Protocol',
    content: 'MEDICAL EMERGENCY RESPONSE PROTOCOL\n\nPurpose: To ensure rapid and effective response to medical emergencies within the stadium.\n\nResponse Time Target: 3 minutes from call to arrival.\n\nProcedure:\n1. Nearest staff member calls for medical support via Radio Channel 3.\n2. Provide: location (section/row/seat), nature of emergency, number of patients.\n3. Clear the area around the affected person.\n4. First aid team responds with emergency kit and AED if cardiac involvement suspected.\n5. If cardiac arrest: begin CPR immediately, retrieve AED from nearest station.\n6. Document incident in the Incident Management System within 30 minutes.\n7. Notify shift supervisor for any severity level 2+ incident.\n\nMedical Station Locations:\n- Station North: Section A, Gate A1 (Staffed 24/7 during events)\n- Station South: Section B, Gate B1 (Staffed 24/7 during events)\n- Station East: Section C, Gate C1 (Staffed during events)\n- Medical Tent West: Section D (Staffed during events)\n\nAED Locations: Each medical station + Gates A3, B2, C2, D1.',
    type: 'emergency',
    language: 'en',
    stadiumId: 'all',
    tags: ['medical', 'emergency', 'first_aid', 'aed', 'response'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Protocol for responding to medical emergencies with 3-minute response target, AED locations, and documentation requirements.',
    metadata: { department: 'Medical', priority: 'critical', reviewCycle: 'annual' },
  },
  {
    title: 'Crowd Surge Management SOP',
    content: 'CROWD SURGE MANAGEMENT STANDARD OPERATING PROCEDURE\n\nPurpose: To prevent and manage crowd surge situations that could endanger fan safety.\n\nThresholds:\n- Yellow (Caution): Zone density > 80% capacity\n- Orange (Warning): Zone density > 90% capacity\n- Red (Critical): Zone density > 95% capacity or crowd movement anomaly detected\n\nProcedure:\n1. Monitor crowd density via CCTV and sensor network.\n2. When Yellow threshold reached: Alert section supervisors, prepare additional staff.\n3. When Orange threshold reached: Deploy crowd management team to affected zone, consider opening overflow gates, PA announcement for alternate routes.\n4. When Red threshold reached: Activate crowd surge protocol, command center takes direct control, consider temporary hold on entry, prepare for potential evacuation.\n\nPrevention Measures:\n- Stagger gate opening times for large sections\n- Deploy crowd ambassadors at high-traffic junctions\n- Real-time density displays at gate entrances\n- Pre-match communication of alternate routes',
    type: 'sop',
    language: 'en',
    stadiumId: 'all',
    tags: ['crowd', 'density', 'surge', 'safety', 'management'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'SOP for preventing and managing crowd surge situations with tiered response thresholds.',
    metadata: { department: 'Security', priority: 'high', reviewCycle: 'annual' },
  },
  {
    title: 'Severe Weather Contingency Plan',
    content: 'SEVERE WEATHER CONTINGENCY PLAN\n\nPurpose: To ensure safe operations during severe weather events.\n\nWeather Triggers:\n- Lightning within 10 miles: Suspend outdoor activities, move fans to covered areas\n- Lightning within 5 miles: Full shelter-in-place, postpone/cancel match\n- Tornado Warning: Activate shelter-in-place, fans to interior corridors\n- Extreme Heat (35°C+): Activate heat safety protocol, increase water distribution\n- Heavy Rain: Monitor field conditions, prepare for delay\n\nProcedure:\n1. Weather monitoring team tracks conditions via National Weather Service alerts.\n2. When trigger reached, command center broadcasts weather advisory.\n3. Staff guide fans to designated shelter areas.\n4. Pitch crew covers field if rain/hail expected.\n5. Match may be delayed or postponed per FIFA regulations.\n6. All-clear issued only when conditions improve and safety confirmed.\n\nShelter Areas:\n- North: Concourse Level 1, Sections A1-A4\n- South: Concourse Level 1, Sections B1-B4\n- East: Upper Level Concourse, Section C\n- West: Lower Level Concourse, Section D\n- VIP: Interior VIP Lounge areas',
    type: 'weather_contingency',
    language: 'en',
    stadiumId: 'all',
    tags: ['weather', 'lightning', 'tornado', 'heat', 'contingency'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Contingency plan for severe weather including lightning, tornado, extreme heat, and heavy rain scenarios.',
    metadata: { department: 'Operations', priority: 'high', reviewCycle: 'annual' },
  },
  {
    title: 'Security Threat Assessment Protocol',
    content: 'SECURITY THREAT ASSESSMENT PROTOCOL\n\nPurpose: To categorize and respond to security threats in a standardized manner.\n\nThreat Levels:\n- Level 1 (Low): Minor disturbance, non-threatening, staff-level resolution\n- Level 2 (Medium): Potential escalation, supervisor involvement required\n- Level 3 (High): Active threat, command center notification mandatory\n- Level 4 (Critical): Imminent danger, lockdown protocol activated\n\nProcedure:\n1. Report suspicious activity immediately via Radio Channel 2.\n2. Security team assesses threat level based on criteria.\n3. Level 1: Staff handles per standard procedures.\n4. Level 2: Supervisor notified, additional security deployed.\n5. Level 3: Command center activated, all security teams on standby, consider partial evacuation.\n6. Level 4: Full lockdown, law enforcement notified, evacuation may be ordered.\n\nReporting Requirements:\n- All Level 2+ incidents require written report within 2 hours\n- Level 3+ incidents require command center log entry\n- CCTV footage preserved for all incidents',
    type: 'sop',
    language: 'en',
    stadiumId: 'all',
    tags: ['security', 'threat', 'assessment', 'lockdown'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Protocol for categorizing security threats from Level 1 (low) to Level 4 (critical) with response procedures.',
    metadata: { department: 'Security', priority: 'critical', reviewCycle: 'annual' },
  },
  {
    title: 'Gate Operations and Entry Procedures',
    content: 'GATE OPERATIONS AND ENTRY PROCEDURES\n\nPurpose: To ensure efficient and secure fan entry through stadium gates.\n\nGate Schedule:\n- Gates open: 2 hours before kickoff\n- Gate closure: 30 minutes after kickoff (late entry via Gate G only)\n- VIP Gate (E): Opens 2.5 hours before kickoff\n\nEntry Procedure:\n1. Ticket verification (digital or printed)\n2. Bag check and prohibited items screening\n3. Security wand/metal detector scan\n4. Wristband issuance for age-restricted areas\n5. Directional guidance to section\n\nGate Assignments:\n- Gate A (North Main): Sections A1-A4, general entry\n- Gate B (South Main): Sections B1-B4, general entry\n- Gate C (East Entry): Sections C1-C3, accessible entry\n- Gate D (West Entry): Sections D1-D3, staff entry\n- Gate E (VIP Entrance): VIP sections V1-V2\n- Gate F (General Admission): GA sections\n- Gate G (Family Entry): Family sections A5-A6\n- Gate H (South Auxiliary): Emergency overflow\n\nWait Time Management:\n- Target: < 10 minutes per gate\n- Overflow protocol: Redirect to adjacent gate\n- Express lane: Clear bags, no carry-on items',
    type: 'policy',
    language: 'en',
    stadiumId: 'all',
    tags: ['gates', 'entry', 'operations', 'ticket', 'screening'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Gate operations including schedule, entry procedure, gate assignments, and wait time management.',
    metadata: { department: 'Operations', priority: 'high', reviewCycle: 'annual' },
  },
  {
    title: 'Prohibited Items and Entry Rules',
    content: 'PROHIBITED ITEMS AND ENTRY RULES\n\nPurpose: To maintain a safe and enjoyable environment for all fans.\n\nProhibited Items:\n- Outside food and beverages (except sealed water bottles < 1L)\n- Large bags or backpacks (max size: 12" x 6" x 12" / 30cm x 15cm x 30cm)\n- Umbrellas (rain ponchos recommended)\n- Flags or banners over 2 meters in length\n- Noisemakers, air horns, or drums\n- Drones or remote-controlled devices\n- Laser pointers\n- Professional cameras with detachable lenses\n- Weapons of any kind\n- Illegal substances\n- Fireworks or pyrotechnics\n- Political or offensive signage\n\nAllowed Items:\n- Clear bags (12" x 6" x 12" max)\n- Small clutches or purses (4.5" x 6.5" / 11cm x 16cm)\n- Seat cushions (without backs or arms)\n- Rain ponchos\n- Sealed water bottles (< 1L)\n- Baby food and formula (in original containers)\n- Medical equipment (with documentation)\n- Assistive devices\n\nEnforcement:\n- All items subject to inspection\n- Prohibited items must be returned to vehicle or disposed of\n- Repeated violations may result in ejection',
    type: 'prohibited_items',
    language: 'en',
    stadiumId: 'all',
    tags: ['prohibited', 'items', 'entry', 'rules', 'bags'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Complete list of prohibited and allowed items for stadium entry with size restrictions and enforcement policy.',
    metadata: { department: 'Security', priority: 'high', reviewCycle: 'annual' },
  },
  {
    title: 'Accessibility Services Guide',
    content: 'ACCESSIBILITY SERVICES GUIDE\n\nPurpose: To ensure all fans can enjoy the match-day experience regardless of ability.\n\nWheelchair Accessible Seating:\n- Available in all sections (A-D, V, GA)\n- Companion seats adjacent\n- Ramps at all entrances\n- Elevators to upper levels\n\nAccessible Restrooms:\n- Every level has accessible restrooms\n- Family restrooms in Sections A1, B1, C1, GA1, VIP\n- Adult changing facilities at Guest Services\n\nHearing Assistance:\n- Assistive listening devices at Guest Services\n- Induction loop system in main auditorium\n- ASL interpretation available (72-hour advance request)\n- Visual alerts supplement audio announcements\n\nVisual Assistance:\n- Large print programs at Guest Services\n- Braille programs available upon request\n- High contrast signage throughout venue\n- Audio descriptions available\n\nSensory Support:\n- Sensory rooms in Sections A3 and B3\n- Low-stimulation environment\n- Noise-canceling headphones available for loan\n- Quiet sections in C1 and D1\n\nService Animals:\n- Welcome in all areas\n- Relief areas at Gate A and Gate C\n- Water bowls at Guest Services\n\nEmergency Evacuation:\n- Evacuation chairs at stairwells\n- Staff trained in disability-aware evacuation\n- Personal Emergency Evacuation Plans (PEEPs) available',
    type: 'accessibility',
    language: 'en',
    stadiumId: 'all',
    tags: ['accessibility', 'wheelchair', 'hearing', 'visual', 'sensory', 'service_animal'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Comprehensive guide to accessibility services including wheelchair access, hearing/visual assistance, and sensory support.',
    metadata: { department: 'Guest Services', priority: 'high', reviewCycle: 'annual' },
  },
  {
    title: 'Transport and Exit Advisory',
    content: 'TRANSPORT AND EXIT ADVISORY\n\nPurpose: To provide fans with post-match transport options and exit guidance.\n\nPublic Transport:\n- Metro Line A (North Station): 3-min frequency, last train 12:30 AM\n- Metro Line B (South Station): 5-min frequency, last train 12:00 AM\n- Shuttle to City Center (East Stop): 8-min frequency, last shuttle 11:00 PM\n- Bus Route 42 (West Stop): 12-min frequency, last bus 11:30 PM\n\nTaxi and Rideshare:\n- Taxi Stand: South Exit, ~2 min wait, fixed fare $25 to downtown\n- Rideshare Pickup: East Zone, ~5 min wait, surge pricing common post-match\n\nParking:\n- Lot North: 2,000 spaces, exit via North Exit A\n- Lot South: 1,500 spaces, exit via South Exit B\n- Garage East: 1,000 spaces, exit via East Exit C\n- VIP Parking: 500 spaces, exit via VIP Entrance\n- Accessible parking in Garage East\n\nExit Strategy:\n- Low congestion: East Exit C, West Exit D\n- Medium congestion: North Exit A, Parking Exit North\n- High congestion: South Exit B, Parking Exit South\n- Wait 15-20 minutes post-match for congestion to ease\n- Check real-time transport updates in app\n\nAccessibility:\n- Wheelchair accessible transport available\n- Golf cart transport from parking to gates\n- Accessible shuttle service',
    type: 'transport',
    language: 'en',
    stadiumId: 'all',
    tags: ['transport', 'exit', 'metro', 'shuttle', 'parking', 'rideshare'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Post-match transport options including public transit, taxi, rideshare, parking, and exit strategy with congestion levels.',
    metadata: { department: 'Operations', priority: 'medium', reviewCycle: 'annual' },
  },
  {
    title: 'Fan Services FAQ',
    content: 'FAN SERVICES FREQUENTLY ASKED QUESTIONS\n\nQ: What time do gates open?\nA: Gates open 2 hours before kickoff. For evening matches, that is 5:00 PM. VIP Gate E opens 2.5 hours before kickoff.\n\nQ: What can I bring into the stadium?\nA: Allowed: clear bags (max 12x6x12 inches), small clutches (4.5x6.5 inches), seat cushions, rain ponchos, sealed water bottles (<1L). Prohibited: outside food/drinks, large bags, umbrellas, flags over 2m, noisemakers, drones.\n\nQ: How do I find my seat?\nA: Your seat is printed on your ticket. Look for your section letter (A-D, V, or GA), then row number, then seat number. Digital tickets have a QR code that staff can scan.\n\nQ: How do I pay for food and drinks?\nA: All concession stands accept contactless payments (credit/debit cards, Apple Pay, Google Pay). Cash accepted at select locations marked with CASH signs.\n\nQ: Is there WiFi in the stadium?\nA: Yes! Free WiFi available. Connect to FIFA2026-Fan network. No password needed.\n\nQ: What should I do in an emergency?\nA: Stay calm, follow staff instructions, use nearest marked exit, do NOT use elevators. Alert staff if you need medical help.\n\nQ: What accessibility services are available?\nA: Wheelchair seating in all sections, companion seats, accessible restrooms, assistive listening devices, sensory rooms in A3 and B3.\n\nQ: I lost something. What should I do?\nA: Visit any Guest Services desk or use the Get Help button in the app. Describe the item and where you last had it.',
    type: 'faq',
    language: 'en',
    stadiumId: 'all',
    tags: ['faq', 'fan', 'services', 'questions', 'answers'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Frequently asked questions about stadium entry, seating, payment, WiFi, safety, accessibility, and lost-and-found.',
    metadata: { department: 'Guest Services', priority: 'medium', reviewCycle: 'annual' },
  },
  {
    title: 'Evacuation Rerouting Playbook',
    content: 'EVACUATION REROUTING PLAYBOOK\n\nPurpose: To provide specific rerouting plans for different evacuation scenarios.\n\nScenario 1: Partial Evacuation (One Zone)\n- Affected zone fans directed to nearest exit\n- Adjacent zones use alternate routes\n- Non-affected zones remain in place\n- Command center monitors and coordinates\n\nScenario 2: Full Evacuation\n- All gates opened simultaneously\n- PA announcement in all 4 languages\n- Fans directed to nearest exit per zone map\n- Staff positioned at all junctions\n- Medical teams at rally points\n- Head count at rally points\n\nScenario 3: Targeted Evacuation (Security Threat)\n- Affected section evacuated first\n- Adjacent sections on standby\n- Security sweep of evacuated area\n- Fans held at rally points until cleared\n\nRerouting Map:\n- North Zone (A): Primary - Gate A, Backup - Gate G\n- South Zone (B): Primary - Gate B, Backup - Gate H\n- East Zone (C): Primary - Gate C\n- West Zone (D): Primary - Gate D, Backup - Gate A\n- VIP Zone (V): Primary - Gate E\n- General Admission (GA): Primary - Gate F\n\nCommunication:\n- Radio Channel 1: Command\n- Radio Channel 2: Security\n- Radio Channel 3: Medical\n- PA System: Fan announcements\n- Digital Displays: Route guidance',
    type: 'evacuation',
    language: 'en',
    stadiumId: 'all',
    tags: ['evacuation', 'rerouting', 'playbook', 'emergency', 'routing'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Rerouting plans for partial, full, and targeted evacuation scenarios with zone-specific exit assignments.',
    metadata: { department: 'Operations', priority: 'critical', reviewCycle: 'annual' },
  },
  {
    title: 'Alcohol Service Policy',
    content: 'ALCOHOL SERVICE POLICY\n\nPurpose: To ensure responsible alcohol service throughout the venue.\n\nService Hours:\n- Service begins: Gates open\n- Service ends: Halftime (no alcohol service in second half)\n- Last call: 5 minutes before halftime\n\nService Limits:\n- Maximum 2 drinks per transaction\n- No service to visibly intoxicated persons\n- Age verification required (21+ for alcoholic beverages)\n- Wristband system for age verification\n\nStaff Requirements:\n- All alcohol service staff must complete alcohol awareness training\n- Training certification required annually\n- Staff must check ID for every alcohol purchase\n- Refusal protocol: Politely decline, offer non-alcoholic alternatives\n\nEnforcement:\n- Intoxicated fans may be removed without refund\n- Repeated violations result in season ban\n- Security notified of aggressive behavior\n\nNon-Alcoholic Options:\n- Water stations throughout venue (free)\n- Soft drinks at all concession stands\n- Coffee kiosks in Sections C and D',
    type: 'policy',
    language: 'en',
    stadiumId: 'all',
    tags: ['alcohol', 'service', 'policy', 'intoxication', 'age_verification'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Alcohol service policy including hours, limits, age verification, staff training, and enforcement procedures.',
    metadata: { department: 'Operations', priority: 'medium', reviewCycle: 'annual' },
  },
  {
    title: 'Lost Child Protocol (Code Adam)',
    content: 'LOST CHILD PROTOCOL (CODE ADAM)\n\nPurpose: To ensure rapid and effective response when a child is reported missing.\n\nTrigger: Any report of a missing child under 12 years old.\n\nProcedure:\n1. Receive report: Child name, age, description, last known location, parent/guardian contact.\n2. Immediately notify security via Radio Channel 2: "Code Adam, [description]".\n3. Staff at all exits are alerted and watch for matching description.\n4. PA announcement with child description (do not use child name publicly).\n5. Search teams deploy to last known location and surrounding areas.\n6. Parent/guardian stays at designated meeting point (Guest Services).\n7. Child found: Verify with parent/guardian, notify command center.\n8. Child not found within 15 minutes: Escalate to law enforcement.\n\nDescription Format:\n- Age, height, weight\n- Hair color and style\n- Clothing description\n- Any distinguishing features\n- Last known location and time\n\nMeeting Points:\n- Primary: Guest Services Desk (Main Concourse)\n- Backup: Security Office (Gate A)\n\nPrevention:\n- Wristband system for young children with parent contact\n- Child-safe zones in family sections\n- Regular announcements about supervision',
    type: 'emergency',
    language: 'en',
    stadiumId: 'all',
    tags: ['lost', 'child', 'code_adam', 'missing', 'emergency'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Code Adam protocol for responding to missing children including search procedures, communication, and escalation.',
    metadata: { department: 'Security', priority: 'critical', reviewCycle: 'annual' },
  },
  {
    title: 'Incident Reporting Policy',
    content: 'INCIDENT REPORTING POLICY\n\nPurpose: To ensure consistent and timely reporting of all incidents.\n\nReporting Timeline:\n- All incidents: Within 30 minutes of occurrence\n- Severity Level 1-2: Shift supervisor notification\n- Severity Level 3+: Command center notification immediately\n- Severity Level 4: Law enforcement notification required\n\nIncident Report Form Required Fields:\n- Date and time of incident\n- Exact location (section, row, seat or gate)\n- Description of incident\n- Persons involved (witnesses, subjects)\n- Actions taken\n- Severity level assessment\n- Reporting staff member ID\n\nSeverity Classification:\n- Level 1: Minor (no injury, no property damage)\n- Level 2: Moderate (minor injury or property damage)\n- Level 3: Serious (significant injury or threat)\n- Level 4: Critical (life-threatening or major incident)\n\nEscalation:\n- Level 1-2: Document and notify supervisor\n- Level 3: Immediate command center notification, written report within 2 hours\n- Level 4: Immediate command center, law enforcement, written report within 1 hour\n\nDocumentation:\n- All reports stored in Incident Management System\n- CCTV footage preserved for Level 2+ incidents\n- Weekly review by operations manager\n- Monthly summary to stadium management',
    type: 'policy',
    language: 'en',
    stadiumId: 'all',
    tags: ['incident', 'reporting', 'documentation', 'severity', 'escalation'],
    effectiveDate: '2026-06-01',
    lastReviewedBy: 'admin@stadiumos.com',
    lastReviewedAt: '2026-06-01T00:00:00Z',
    createdBy: 'admin@stadiumos.com',
    summary: 'Incident reporting requirements including timelines, severity classification, escalation paths, and documentation standards.',
    metadata: { department: 'Operations', priority: 'high', reviewCycle: 'annual' },
  },
];

export async function loadSeedDocumentsFromDB(): Promise<Omit<KnowledgeDocument, 'id' | 'version' | 'status' | 'createdAt' | 'updatedAt'>[]> {
  try {
    const { prisma } = await import('@/lib/prisma');
    const docs = await prisma.knowledgeDocument.findMany({
      where: {
        isDeleted: false,
      },
    });

    if (docs.length === 0) {
      return SEED_DOCUMENTS;
    }

    return docs.map((doc) => ({
      title: doc.title,
      content: doc.content,
      type: doc.category as KnowledgeDocumentType,
      language: doc.language as KnowledgeLanguage,
      stadiumId: doc.stadiumId || 'all',
      tags: JSON.parse(doc.tags || '[]'),
      effectiveDate: doc.createdAt.toISOString().split('T')[0],
      lastReviewedBy: doc.createdBy,
      lastReviewedAt: doc.updatedAt.toISOString(),
      createdBy: doc.createdBy,
      summary: doc.title,
      metadata: {},
    }));
  } catch (error) {
    console.warn('Failed to load seed documents from DB:', error);
    return SEED_DOCUMENTS;
  }
}
